### PR TITLE
Feature #215 - Add package description

### PR DESCRIPTION
**Pull request by mfjurbala**
This adds the ability to view or hide detailed package description to address Development Management item #41 ([Feature] Adding packages description window to Software Station#215).

Let me know of any changes or improvements. 

Thanks

### CODE REVIEW

**Review by ericbsd — COMMENTED** [review]
This is what I get when I run the code.

image

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/ghostbsd-src/issues/215 was not well-defined, but my idea was to click on the package in the list and replace the interface. 

By interface, I mean this:
image

That is why there is a back and forward button.

Has what you did it fine but it will be replaced in the future.

**Comment by mfjurbala** [comment]
I wondered why the back button was there but it didn't seem to do anything. This is what I am looking at and the tooltip on hover should show the description, I might have messed something up though. And no worries, if you want this in the meantime take it, if it would make more work just send it back.

no_pkg
pkg

**Comment by ericbsd** [comment]
Oh wait, I think I install it from the wrong branch.

**Comment by ericbsd** [comment]
OK, that is working, not that I am the right branch.
image

**Comment by ericbsd** [comment]
That would be nice if all URLs could be clickable, but that could be done later.

Oh, before I get that merge, could you bump the version in the `software-station` file `1.7`

**Comment by mfjurbala** [comment]
Sure I'll do that maybe today or over the weekend.

**Comment by mfjurbala** [comment]
The version is bumped and I had to mix a small fix to actually hide the description window.

I started to make the URL clickable but since software-station is running as root, it tries to open the browser as root which fails. I'm not sure if this is from me running `sudo ./software-station` to test or if it will always happen.

If it will always happen I wonder if we could or should make something like an administrator group that can run pkg commands.

**Review by ericbsd — APPROVED** [review]
LGTM

**Pull request merged**
